[package]
name = "n_crypt"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# GUI
eframe = "0.31.0"
rfd = "0.14.1"
egui-theme = {git = "https://github.com/greekfetacheese/egui-theme.git", branch = "master"}

# Crypto
sha3 = "0.10.8"
ncrypt-me = { git = "https://github.com/greekfetacheese/ncrypt-me.git", branch = "master" }

# Misc
num-format = "0.4.4"